[package]
name = "resistor_bank"
version = "0.1.1"
edition = "2024"

[dependencies]
atoll = { version = "0.1.4", registry = "substrate", path = "../../../libs/atoll" }
substrate = { version = "0.10.3", registry = "substrate", path = "../../../substrate" }
sky130 = { version = "0.10.3", registry = "substrate", path = "../../../pdks/sky130" }
layir = { version = "0.2.2", registry = "substrate", path = "../../../libs/layir" }
gdsconv = { version = "0.2.2", registry = "substrate", path = "../../../libs/gdsconv" }
gds = { version = "0.4.2", registry = "substrate", path = "../../../libs/gds" }
scir = { version = "0.9.2", registry = "substrate", path = "../../../libs/scir" }
spice = { version = "0.9.3", registry = "substrate", path = "../../../libs/spice" }

arcstr = "1"
rust_decimal = "1"
rust_decimal_macros = "1"
derive-where = "1"

