[workspace]

resolver = "2"

members = [
    "cache",
    "cli",
    "codegen",
    "dex",
    "digital",
    "drc",
    "gds",
    "geometry",
    "layout",
    "lef",
    "lvs",
    "par",
    "pex",
    "sbm",
    "scg",
    "schematic",
    "sde",
    "sim",
    "subfile",
    "substrate",
    "tests",
    "timing",
]
