[package]
name = "magic_netgen"
version = "0.1.4"
edition = "2024"

[dependencies]
substrate = { version = "0.10.3", registry = "substrate", path = "../../substrate" }
scir = { version = "0.9.2", registry = "substrate", path = "../../libs/scir" }
spice = { version = "0.9.3", registry = "substrate", path = "../../libs/spice" }
magic = { version = "0.2.2", registry = "substrate", path = "../magic" }
netgen = { version = "0.2.2", registry = "substrate", path = "../netgen" }
