[package]
name = "colbuf"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
substrate = { version = "0.10.2", registry = "substrate" }
spice = { version = "0.9.2", registry = "substrate" }
spectre = { version = "0.11.2", registry = "substrate" }
ngspice = { version = "0.5.2", registry = "substrate" }
quantus = { version = "0.2.2", registry = "substrate" }
magic_netgen = { version = "0.1.3", registry = "substrate" }
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"

[dev-dependencies]
approx = "0.5"
