[package]
name = "colbuf"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
substrate = { version = "0.10.3", registry = "substrate" }
spice = { version = "0.9.3", registry = "substrate" }
spectre = { version = "0.11.3", registry = "substrate" }
ngspice = { version = "0.5.3", registry = "substrate" }
quantus = { version = "0.2.3", registry = "substrate" }
magic_netgen = { version = "0.1.4", registry = "substrate" }
rust_decimal = "1.37.1"
rust_decimal_macros = "1.37.1"

[dev-dependencies]
sky130 = { version = "<=0.10.3", registry = "substrate" }
approx = "0.5"
