[package]
name = "substrate_api_examples"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
substrate = { version = "0.10.1", registry = "substrate" }
scir = { version = "0.9.1", registry = "substrate" }

arcstr = "1"
rust_decimal = "1"
