[package]
name = "quantus"
version = "0.2.1"
edition = "2021"

[dependencies]
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
regex = "1"

substrate = { version = "0.10.1", registry = "substrate", path = "../../substrate" }
scir = { version = "0.9.0", registry = "substrate", path = "../../libs/scir" }
spice = { version = "0.9.1", registry = "substrate", path = "../../libs/spice" }
pegasus = { version = "0.2.0", registry = "substrate", path = "../pegasus" }

[dev-dependencies]
rust_decimal = "1"
