[package]
name = "quantus"
version = "0.2.2"
edition = "2024"

[dependencies]
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
regex = "1"

substrate = { version = "0.10.2", registry = "substrate", path = "../../substrate" }
scir = { version = "0.9.1", registry = "substrate", path = "../../libs/scir" }
spice = { version = "0.9.2", registry = "substrate", path = "../../libs/spice" }
pegasus = { version = "0.2.1", registry = "substrate", path = "../pegasus" }

[dev-dependencies]
sky130 = { version = "0.10.2", registry = "substrate", path = "../../pdks/sky130" }
rust_decimal = "1"
