[package]
name = "strongarm"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
atoll = { version = "0.1.3", registry = "substrate", path = "../../../libs/atoll" }
substrate = { version = "0.10.2", registry = "substrate", path = "../../../substrate" }
sky130 = { version = "0.10.2", registry = "substrate", path = "../../../pdks/sky130" }
layir = { version = "0.2.1", registry = "substrate", path = "../../../libs/layir" }
gdsconv = { version = "0.2.1", registry = "substrate", path = "../../../libs/gdsconv" }
gds = { version = "0.4.1", registry = "substrate", path = "../../../libs/gds" }
scir = { version = "0.9.1", registry = "substrate", path = "../../../libs/scir" }
spice = { version = "0.9.2", registry = "substrate", path = "../../../libs/spice" }

arcstr = "1"
rust_decimal = "1"
rust_decimal_macros = "1"
derive-where = "1"
approx = "0.5"
itertools = "0.14"

spectre = { version = "0.11.2", registry = "substrate", path = "../../../tools/spectre" }
quantus = { version = "0.2.2", registry = "substrate", path = "../../../tools/quantus" }
pegasus = { version = "0.2.1", registry = "substrate", path = "../../../tools/pegasus" }

[dev-dependencies]
plotters = "0.3"
