[package]
name = "colbuf"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
substrate = { version = "0.10.3", registry = "substrate", path = "../../../substrate" }
spice = { version = "0.9.3", registry = "substrate", path = "../../../libs/spice" }
spectre = { version = "0.11.3", registry = "substrate", path = "../../../tools/spectre" }
ngspice = { version = "0.5.3", registry = "substrate", path = "../../../tools/ngspice" }
quantus = { version = "0.2.3", registry = "substrate", path = "../../../tools/quantus" }
magic_netgen = { version = "0.1.4", registry = "substrate", path = "../../../tools/magic_netgen" }
rust_decimal = "1.40.0"
rust_decimal_macros = "1.40.0"

[dev-dependencies]
sky130 = { version = "<=0.10.3", registry = "substrate", path = "../../../pdks/sky130" }
approx = "0.5"
