[package]
name = "spectre"
version = "0.11.2"
edition = "2024"

[dependencies]
rust_decimal = "1"
rust_decimal_macros = "1"
thiserror = "2"
arcstr = { version = "1", features = ["serde"] }
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
itertools = "0.14"
regex = "1"
num = { version = "0.4", features = ["serde"] }

cache = { version = "0.7.1", registry = "substrate", path = "../../libs/cache" }
psfparser = { version = "0.1.4", registry = "substrate", path = "../../libs/psfparser" }
scir = { version = "0.9.1", registry = "substrate", path = "../../libs/scir" }
substrate = { version = "0.10.2", registry = "substrate", path = "../../substrate" }
spice = { version = "0.9.2", registry = "substrate", path = "../../libs/spice" }
type_dispatch = { version = "0.5.1", registry = "substrate", path = "../../libs/type_dispatch" }

[dev-dependencies]
approx = "0.5"
