[package]
name = "magic"
version = "0.3.0"
edition = "2021"

[dependencies]
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
regex = "1"
itertools = "0.14.0"
thiserror = "2.0.11"
