[package]
name = "magic"
version = "0.2.2"
edition = "2024"

[dependencies]
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
regex = "1"
itertools = "0.14.0"
thiserror = "2.0.12"

[dev-dependencies]
sky130 = { version = "<=0.10.3", registry = "substrate", path = "../../pdks/sky130" }
