[package]
name = "substrate_api_examples"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
substrate = { version = "0.10.3", registry = "substrate", path = "../../../substrate" }
scir = { version = "0.9.2", registry = "substrate", path = "../../../libs/scir" }

arcstr = "1"
rust_decimal = "1"
