[package]
name = "ngspice"
version = "0.0.0"
edition = "2021"

[dependencies]
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
thiserror = "1"
arcstr = { version = "1", features = [ "serde" ] }
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
indexmap = { version = "2", features = ["serde"] }

cache = { version = "0.3.1", registry = "substrate", path = "../../libs/cache" }
scir = { version = "0.5.0", registry = "substrate", path = "../../libs/scir" }
substrate = { version = "0.6.1", registry = "substrate", path = "../../substrate" }
nutlex = { version = "0.1.0", registry = "substrate", path = "../../libs/nutlex" }
