[package]
name = "vdivider"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
arcstr = { version = "1", features = ["serde"] }
rust_decimal = "1"
rust_decimal_macros = "1"
serde = { version = "1.0.219", features = ["derive"] }
substrate = { version = "0.10.3", registry = "substrate" }
spectre = { version = "0.11.3", registry = "substrate" }

[dev-dependencies]
approx = "0.5"
